// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: block_storage.proto

package com.twitter.data.proto;

public final class BlockStorage {
  private BlockStorage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SerializedBlock extends
      com.google.protobuf.GeneratedMessage {
    // Use SerializedBlock.newBuilder() to construct.
    private SerializedBlock() {
      initFields();
    }
    private SerializedBlock(boolean noInit) {}
    
    private static final SerializedBlock defaultInstance;
    public static SerializedBlock getDefaultInstance() {
      return defaultInstance;
    }
    
    public SerializedBlock getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.twitter.data.proto.BlockStorage.internal_static_com_twitter_data_proto_SerializedBlock_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.twitter.data.proto.BlockStorage.internal_static_com_twitter_data_proto_SerializedBlock_fieldAccessorTable;
    }
    
    // optional int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private boolean hasVersion;
    private int version_ = 0;
    public boolean hasVersion() { return hasVersion; }
    public int getVersion() { return version_; }
    
    // optional string proto_class_name = 2;
    public static final int PROTO_CLASS_NAME_FIELD_NUMBER = 2;
    private boolean hasProtoClassName;
    private java.lang.String protoClassName_ = "";
    public boolean hasProtoClassName() { return hasProtoClassName; }
    public java.lang.String getProtoClassName() { return protoClassName_; }
    
    // repeated bytes proto_blobs = 3;
    public static final int PROTO_BLOBS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> protoBlobs_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getProtoBlobsList() {
      return protoBlobs_;
    }
    public int getProtoBlobsCount() { return protoBlobs_.size(); }
    public com.google.protobuf.ByteString getProtoBlobs(int index) {
      return protoBlobs_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVersion()) {
        output.writeInt32(1, getVersion());
      }
      if (hasProtoClassName()) {
        output.writeString(2, getProtoClassName());
      }
      for (com.google.protobuf.ByteString element : getProtoBlobsList()) {
        output.writeBytes(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getVersion());
      }
      if (hasProtoClassName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getProtoClassName());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getProtoBlobsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getProtoBlobsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.data.proto.BlockStorage.SerializedBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.twitter.data.proto.BlockStorage.SerializedBlock prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.twitter.data.proto.BlockStorage.SerializedBlock result;
      
      // Construct using com.twitter.data.proto.BlockStorage.SerializedBlock.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.twitter.data.proto.BlockStorage.SerializedBlock();
        return builder;
      }
      
      protected com.twitter.data.proto.BlockStorage.SerializedBlock internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.twitter.data.proto.BlockStorage.SerializedBlock();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.twitter.data.proto.BlockStorage.SerializedBlock.getDescriptor();
      }
      
      public com.twitter.data.proto.BlockStorage.SerializedBlock getDefaultInstanceForType() {
        return com.twitter.data.proto.BlockStorage.SerializedBlock.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.twitter.data.proto.BlockStorage.SerializedBlock build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.twitter.data.proto.BlockStorage.SerializedBlock buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.twitter.data.proto.BlockStorage.SerializedBlock buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.protoBlobs_ != java.util.Collections.EMPTY_LIST) {
          result.protoBlobs_ =
            java.util.Collections.unmodifiableList(result.protoBlobs_);
        }
        com.twitter.data.proto.BlockStorage.SerializedBlock returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.twitter.data.proto.BlockStorage.SerializedBlock) {
          return mergeFrom((com.twitter.data.proto.BlockStorage.SerializedBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.twitter.data.proto.BlockStorage.SerializedBlock other) {
        if (other == com.twitter.data.proto.BlockStorage.SerializedBlock.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasProtoClassName()) {
          setProtoClassName(other.getProtoClassName());
        }
        if (!other.protoBlobs_.isEmpty()) {
          if (result.protoBlobs_.isEmpty()) {
            result.protoBlobs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.protoBlobs_.addAll(other.protoBlobs_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setVersion(input.readInt32());
              break;
            }
            case 18: {
              setProtoClassName(input.readString());
              break;
            }
            case 26: {
              addProtoBlobs(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional int32 version = 1;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public int getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(int value) {
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = 0;
        return this;
      }
      
      // optional string proto_class_name = 2;
      public boolean hasProtoClassName() {
        return result.hasProtoClassName();
      }
      public java.lang.String getProtoClassName() {
        return result.getProtoClassName();
      }
      public Builder setProtoClassName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProtoClassName = true;
        result.protoClassName_ = value;
        return this;
      }
      public Builder clearProtoClassName() {
        result.hasProtoClassName = false;
        result.protoClassName_ = getDefaultInstance().getProtoClassName();
        return this;
      }
      
      // repeated bytes proto_blobs = 3;
      public java.util.List<com.google.protobuf.ByteString> getProtoBlobsList() {
        return java.util.Collections.unmodifiableList(result.protoBlobs_);
      }
      public int getProtoBlobsCount() {
        return result.getProtoBlobsCount();
      }
      public com.google.protobuf.ByteString getProtoBlobs(int index) {
        return result.getProtoBlobs(index);
      }
      public Builder setProtoBlobs(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.protoBlobs_.set(index, value);
        return this;
      }
      public Builder addProtoBlobs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.protoBlobs_.isEmpty()) {
          result.protoBlobs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.protoBlobs_.add(value);
        return this;
      }
      public Builder addAllProtoBlobs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.protoBlobs_.isEmpty()) {
          result.protoBlobs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.protoBlobs_);
        return this;
      }
      public Builder clearProtoBlobs() {
        result.protoBlobs_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.twitter.data.proto.SerializedBlock)
    }
    
    static {
      defaultInstance = new SerializedBlock(true);
      com.twitter.data.proto.BlockStorage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.twitter.data.proto.SerializedBlock)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_twitter_data_proto_SerializedBlock_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_twitter_data_proto_SerializedBlock_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023block_storage.proto\022\026com.twitter.data." +
      "proto\"Q\n\017SerializedBlock\022\017\n\007version\030\001 \001(" +
      "\005\022\030\n\020proto_class_name\030\002 \001(\t\022\023\n\013proto_blo" +
      "bs\030\003 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_twitter_data_proto_SerializedBlock_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_twitter_data_proto_SerializedBlock_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_twitter_data_proto_SerializedBlock_descriptor,
              new java.lang.String[] { "Version", "ProtoClassName", "ProtoBlobs", },
              com.twitter.data.proto.BlockStorage.SerializedBlock.class,
              com.twitter.data.proto.BlockStorage.SerializedBlock.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
