// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tap.proto

package tap.sample;

public final class Tap {
  private Tap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum OptionType
      implements com.google.protobuf.ProtocolMessageEnum {
    PUT(0, 0),
    CALL(1, 1),
    ;
    
    public static final int PUT_VALUE = 0;
    public static final int CALL_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static OptionType valueOf(int value) {
      switch (value) {
        case 0: return PUT;
        case 1: return CALL;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<OptionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<OptionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OptionType>() {
            public OptionType findValueByNumber(int number) {
              return OptionType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return tap.sample.Tap.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final OptionType[] VALUES = {
      PUT, CALL, 
    };
    
    public static OptionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private OptionType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:tap.sample.OptionType)
  }
  
  public interface TimestampOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional sint64 ticks = 1;
    boolean hasTicks();
    long getTicks();
    
    // optional sint64 provider_time = 2;
    boolean hasProviderTime();
    long getProviderTime();
    
    // optional sint64 exchange_time = 3;
    boolean hasExchangeTime();
    long getExchangeTime();
  }
  public static final class Timestamp extends
      com.google.protobuf.GeneratedMessage
      implements TimestampOrBuilder {
    // Use Timestamp.newBuilder() to construct.
    private Timestamp(Builder builder) {
      super(builder);
    }
    private Timestamp(boolean noInit) {}
    
    private static final Timestamp defaultInstance;
    public static Timestamp getDefaultInstance() {
      return defaultInstance;
    }
    
    public Timestamp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.sample.Tap.internal_static_tap_sample_Timestamp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.sample.Tap.internal_static_tap_sample_Timestamp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional sint64 ticks = 1;
    public static final int TICKS_FIELD_NUMBER = 1;
    private long ticks_;
    public boolean hasTicks() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTicks() {
      return ticks_;
    }
    
    // optional sint64 provider_time = 2;
    public static final int PROVIDER_TIME_FIELD_NUMBER = 2;
    private long providerTime_;
    public boolean hasProviderTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getProviderTime() {
      return providerTime_;
    }
    
    // optional sint64 exchange_time = 3;
    public static final int EXCHANGE_TIME_FIELD_NUMBER = 3;
    private long exchangeTime_;
    public boolean hasExchangeTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getExchangeTime() {
      return exchangeTime_;
    }
    
    private void initFields() {
      ticks_ = 0L;
      providerTime_ = 0L;
      exchangeTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, ticks_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt64(2, providerTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt64(3, exchangeTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, ticks_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, providerTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, exchangeTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.sample.Tap.Timestamp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Timestamp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Timestamp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Timestamp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.sample.Tap.Timestamp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.sample.Tap.TimestampOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.sample.Tap.internal_static_tap_sample_Timestamp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.sample.Tap.internal_static_tap_sample_Timestamp_fieldAccessorTable;
      }
      
      // Construct using tap.sample.Tap.Timestamp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ticks_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        providerTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        exchangeTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.sample.Tap.Timestamp.getDescriptor();
      }
      
      public tap.sample.Tap.Timestamp getDefaultInstanceForType() {
        return tap.sample.Tap.Timestamp.getDefaultInstance();
      }
      
      public tap.sample.Tap.Timestamp build() {
        tap.sample.Tap.Timestamp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.sample.Tap.Timestamp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.sample.Tap.Timestamp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.sample.Tap.Timestamp buildPartial() {
        tap.sample.Tap.Timestamp result = new tap.sample.Tap.Timestamp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticks_ = ticks_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.providerTime_ = providerTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.exchangeTime_ = exchangeTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.sample.Tap.Timestamp) {
          return mergeFrom((tap.sample.Tap.Timestamp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.sample.Tap.Timestamp other) {
        if (other == tap.sample.Tap.Timestamp.getDefaultInstance()) return this;
        if (other.hasTicks()) {
          setTicks(other.getTicks());
        }
        if (other.hasProviderTime()) {
          setProviderTime(other.getProviderTime());
        }
        if (other.hasExchangeTime()) {
          setExchangeTime(other.getExchangeTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ticks_ = input.readSInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              providerTime_ = input.readSInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              exchangeTime_ = input.readSInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional sint64 ticks = 1;
      private long ticks_ ;
      public boolean hasTicks() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTicks() {
        return ticks_;
      }
      public Builder setTicks(long value) {
        bitField0_ |= 0x00000001;
        ticks_ = value;
        onChanged();
        return this;
      }
      public Builder clearTicks() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ticks_ = 0L;
        onChanged();
        return this;
      }
      
      // optional sint64 provider_time = 2;
      private long providerTime_ ;
      public boolean hasProviderTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getProviderTime() {
        return providerTime_;
      }
      public Builder setProviderTime(long value) {
        bitField0_ |= 0x00000002;
        providerTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearProviderTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        providerTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional sint64 exchange_time = 3;
      private long exchangeTime_ ;
      public boolean hasExchangeTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getExchangeTime() {
        return exchangeTime_;
      }
      public Builder setExchangeTime(long value) {
        bitField0_ |= 0x00000004;
        exchangeTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearExchangeTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exchangeTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.sample.Timestamp)
    }
    
    static {
      defaultInstance = new Timestamp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.sample.Timestamp)
  }
  
  public interface InstrumentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 id = 1;
    boolean hasId();
    long getId();
    
    // optional uint32 option_expiration = 2;
    boolean hasOptionExpiration();
    int getOptionExpiration();
    
    // optional uint32 option_strike = 3;
    boolean hasOptionStrike();
    int getOptionStrike();
    
    // optional .tap.sample.OptionType option_type = 4;
    boolean hasOptionType();
    tap.sample.Tap.OptionType getOptionType();
    
    // optional uint32 future_expiration = 5;
    boolean hasFutureExpiration();
    int getFutureExpiration();
  }
  public static final class Instrument extends
      com.google.protobuf.GeneratedMessage
      implements InstrumentOrBuilder {
    // Use Instrument.newBuilder() to construct.
    private Instrument(Builder builder) {
      super(builder);
    }
    private Instrument(boolean noInit) {}
    
    private static final Instrument defaultInstance;
    public static Instrument getDefaultInstance() {
      return defaultInstance;
    }
    
    public Instrument getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.sample.Tap.internal_static_tap_sample_Instrument_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.sample.Tap.internal_static_tap_sample_Instrument_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional uint32 option_expiration = 2;
    public static final int OPTION_EXPIRATION_FIELD_NUMBER = 2;
    private int optionExpiration_;
    public boolean hasOptionExpiration() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getOptionExpiration() {
      return optionExpiration_;
    }
    
    // optional uint32 option_strike = 3;
    public static final int OPTION_STRIKE_FIELD_NUMBER = 3;
    private int optionStrike_;
    public boolean hasOptionStrike() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getOptionStrike() {
      return optionStrike_;
    }
    
    // optional .tap.sample.OptionType option_type = 4;
    public static final int OPTION_TYPE_FIELD_NUMBER = 4;
    private tap.sample.Tap.OptionType optionType_;
    public boolean hasOptionType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public tap.sample.Tap.OptionType getOptionType() {
      return optionType_;
    }
    
    // optional uint32 future_expiration = 5;
    public static final int FUTURE_EXPIRATION_FIELD_NUMBER = 5;
    private int futureExpiration_;
    public boolean hasFutureExpiration() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getFutureExpiration() {
      return futureExpiration_;
    }
    
    private void initFields() {
      id_ = 0L;
      optionExpiration_ = 0;
      optionStrike_ = 0;
      optionType_ = tap.sample.Tap.OptionType.PUT;
      futureExpiration_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, optionExpiration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, optionStrike_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, optionType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, futureExpiration_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, optionExpiration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, optionStrike_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, optionType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, futureExpiration_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.sample.Tap.Instrument parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Instrument parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Instrument parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Instrument parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Instrument parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Instrument parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Instrument parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Instrument parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Instrument parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Instrument parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.sample.Tap.Instrument prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.sample.Tap.InstrumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.sample.Tap.internal_static_tap_sample_Instrument_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.sample.Tap.internal_static_tap_sample_Instrument_fieldAccessorTable;
      }
      
      // Construct using tap.sample.Tap.Instrument.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        optionExpiration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        optionStrike_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        optionType_ = tap.sample.Tap.OptionType.PUT;
        bitField0_ = (bitField0_ & ~0x00000008);
        futureExpiration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.sample.Tap.Instrument.getDescriptor();
      }
      
      public tap.sample.Tap.Instrument getDefaultInstanceForType() {
        return tap.sample.Tap.Instrument.getDefaultInstance();
      }
      
      public tap.sample.Tap.Instrument build() {
        tap.sample.Tap.Instrument result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.sample.Tap.Instrument buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.sample.Tap.Instrument result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.sample.Tap.Instrument buildPartial() {
        tap.sample.Tap.Instrument result = new tap.sample.Tap.Instrument(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.optionExpiration_ = optionExpiration_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.optionStrike_ = optionStrike_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.optionType_ = optionType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.futureExpiration_ = futureExpiration_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.sample.Tap.Instrument) {
          return mergeFrom((tap.sample.Tap.Instrument)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.sample.Tap.Instrument other) {
        if (other == tap.sample.Tap.Instrument.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOptionExpiration()) {
          setOptionExpiration(other.getOptionExpiration());
        }
        if (other.hasOptionStrike()) {
          setOptionStrike(other.getOptionStrike());
        }
        if (other.hasOptionType()) {
          setOptionType(other.getOptionType());
        }
        if (other.hasFutureExpiration()) {
          setFutureExpiration(other.getFutureExpiration());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              optionExpiration_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              optionStrike_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              tap.sample.Tap.OptionType value = tap.sample.Tap.OptionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                optionType_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              futureExpiration_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint32 option_expiration = 2;
      private int optionExpiration_ ;
      public boolean hasOptionExpiration() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getOptionExpiration() {
        return optionExpiration_;
      }
      public Builder setOptionExpiration(int value) {
        bitField0_ |= 0x00000002;
        optionExpiration_ = value;
        onChanged();
        return this;
      }
      public Builder clearOptionExpiration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        optionExpiration_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 option_strike = 3;
      private int optionStrike_ ;
      public boolean hasOptionStrike() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getOptionStrike() {
        return optionStrike_;
      }
      public Builder setOptionStrike(int value) {
        bitField0_ |= 0x00000004;
        optionStrike_ = value;
        onChanged();
        return this;
      }
      public Builder clearOptionStrike() {
        bitField0_ = (bitField0_ & ~0x00000004);
        optionStrike_ = 0;
        onChanged();
        return this;
      }
      
      // optional .tap.sample.OptionType option_type = 4;
      private tap.sample.Tap.OptionType optionType_ = tap.sample.Tap.OptionType.PUT;
      public boolean hasOptionType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public tap.sample.Tap.OptionType getOptionType() {
        return optionType_;
      }
      public Builder setOptionType(tap.sample.Tap.OptionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        optionType_ = value;
        onChanged();
        return this;
      }
      public Builder clearOptionType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        optionType_ = tap.sample.Tap.OptionType.PUT;
        onChanged();
        return this;
      }
      
      // optional uint32 future_expiration = 5;
      private int futureExpiration_ ;
      public boolean hasFutureExpiration() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getFutureExpiration() {
        return futureExpiration_;
      }
      public Builder setFutureExpiration(int value) {
        bitField0_ |= 0x00000010;
        futureExpiration_ = value;
        onChanged();
        return this;
      }
      public Builder clearFutureExpiration() {
        bitField0_ = (bitField0_ & ~0x00000010);
        futureExpiration_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.sample.Instrument)
    }
    
    static {
      defaultInstance = new Instrument(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.sample.Instrument)
  }
  
  public interface ExchangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string mic = 1;
    boolean hasMic();
    String getMic();
  }
  public static final class Exchange extends
      com.google.protobuf.GeneratedMessage
      implements ExchangeOrBuilder {
    // Use Exchange.newBuilder() to construct.
    private Exchange(Builder builder) {
      super(builder);
    }
    private Exchange(boolean noInit) {}
    
    private static final Exchange defaultInstance;
    public static Exchange getDefaultInstance() {
      return defaultInstance;
    }
    
    public Exchange getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.sample.Tap.internal_static_tap_sample_Exchange_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.sample.Tap.internal_static_tap_sample_Exchange_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string mic = 1;
    public static final int MIC_FIELD_NUMBER = 1;
    private java.lang.Object mic_;
    public boolean hasMic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMic() {
      java.lang.Object ref = mic_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mic_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMicBytes() {
      java.lang.Object ref = mic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      mic_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMicBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMicBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.sample.Tap.Exchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Exchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Exchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Exchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Exchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Exchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Exchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Exchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.sample.Tap.Exchange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.sample.Tap.ExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.sample.Tap.internal_static_tap_sample_Exchange_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.sample.Tap.internal_static_tap_sample_Exchange_fieldAccessorTable;
      }
      
      // Construct using tap.sample.Tap.Exchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        mic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.sample.Tap.Exchange.getDescriptor();
      }
      
      public tap.sample.Tap.Exchange getDefaultInstanceForType() {
        return tap.sample.Tap.Exchange.getDefaultInstance();
      }
      
      public tap.sample.Tap.Exchange build() {
        tap.sample.Tap.Exchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.sample.Tap.Exchange buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.sample.Tap.Exchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.sample.Tap.Exchange buildPartial() {
        tap.sample.Tap.Exchange result = new tap.sample.Tap.Exchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mic_ = mic_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.sample.Tap.Exchange) {
          return mergeFrom((tap.sample.Tap.Exchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.sample.Tap.Exchange other) {
        if (other == tap.sample.Tap.Exchange.getDefaultInstance()) return this;
        if (other.hasMic()) {
          setMic(other.getMic());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mic_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string mic = 1;
      private java.lang.Object mic_ = "";
      public boolean hasMic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMic() {
        java.lang.Object ref = mic_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mic_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMic(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mic_ = value;
        onChanged();
        return this;
      }
      public Builder clearMic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mic_ = getDefaultInstance().getMic();
        onChanged();
        return this;
      }
      void setMic(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        mic_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:tap.sample.Exchange)
    }
    
    static {
      defaultInstance = new Exchange(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.sample.Exchange)
  }
  
  public interface CurrencyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string currency = 1;
    boolean hasCurrency();
    String getCurrency();
  }
  public static final class Currency extends
      com.google.protobuf.GeneratedMessage
      implements CurrencyOrBuilder {
    // Use Currency.newBuilder() to construct.
    private Currency(Builder builder) {
      super(builder);
    }
    private Currency(boolean noInit) {}
    
    private static final Currency defaultInstance;
    public static Currency getDefaultInstance() {
      return defaultInstance;
    }
    
    public Currency getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.sample.Tap.internal_static_tap_sample_Currency_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.sample.Tap.internal_static_tap_sample_Currency_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string currency = 1;
    public static final int CURRENCY_FIELD_NUMBER = 1;
    private java.lang.Object currency_;
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          currency_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      currency_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCurrencyBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCurrencyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.sample.Tap.Currency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Currency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Currency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.sample.Tap.Currency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Currency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Currency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.sample.Tap.Currency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Currency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.sample.Tap.Currency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.sample.Tap.Currency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.sample.Tap.Currency prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.sample.Tap.CurrencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.sample.Tap.internal_static_tap_sample_Currency_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.sample.Tap.internal_static_tap_sample_Currency_fieldAccessorTable;
      }
      
      // Construct using tap.sample.Tap.Currency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        currency_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.sample.Tap.Currency.getDescriptor();
      }
      
      public tap.sample.Tap.Currency getDefaultInstanceForType() {
        return tap.sample.Tap.Currency.getDefaultInstance();
      }
      
      public tap.sample.Tap.Currency build() {
        tap.sample.Tap.Currency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.sample.Tap.Currency buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.sample.Tap.Currency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.sample.Tap.Currency buildPartial() {
        tap.sample.Tap.Currency result = new tap.sample.Tap.Currency(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currency_ = currency_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.sample.Tap.Currency) {
          return mergeFrom((tap.sample.Tap.Currency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.sample.Tap.Currency other) {
        if (other == tap.sample.Tap.Currency.getDefaultInstance()) return this;
        if (other.hasCurrency()) {
          setCurrency(other.getCurrency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              currency_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string currency = 1;
      private java.lang.Object currency_ = "";
      public boolean hasCurrency() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCurrency(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        currency_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrency() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      void setCurrency(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        currency_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:tap.sample.Currency)
    }
    
    static {
      defaultInstance = new Currency(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.sample.Currency)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_sample_Timestamp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_sample_Timestamp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_sample_Instrument_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_sample_Instrument_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_sample_Exchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_sample_Exchange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_sample_Currency_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_sample_Currency_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tTap.proto\022\ntap.sample\"H\n\tTimestamp\022\r\n\005" +
      "ticks\030\001 \001(\022\022\025\n\rprovider_time\030\002 \001(\022\022\025\n\rex" +
      "change_time\030\003 \001(\022\"\222\001\n\nInstrument\022\n\n\002id\030\001" +
      " \001(\004\022\031\n\021option_expiration\030\002 \001(\r\022\025\n\roptio" +
      "n_strike\030\003 \001(\r\022+\n\013option_type\030\004 \001(\0162\026.ta" +
      "p.sample.OptionType\022\031\n\021future_expiration" +
      "\030\005 \001(\r\"\027\n\010Exchange\022\013\n\003mic\030\001 \001(\t\"\034\n\010Curre" +
      "ncy\022\020\n\010currency\030\001 \001(\t*\037\n\nOptionType\022\007\n\003P" +
      "UT\020\000\022\010\n\004CALL\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tap_sample_Timestamp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tap_sample_Timestamp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_sample_Timestamp_descriptor,
              new java.lang.String[] { "Ticks", "ProviderTime", "ExchangeTime", },
              tap.sample.Tap.Timestamp.class,
              tap.sample.Tap.Timestamp.Builder.class);
          internal_static_tap_sample_Instrument_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tap_sample_Instrument_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_sample_Instrument_descriptor,
              new java.lang.String[] { "Id", "OptionExpiration", "OptionStrike", "OptionType", "FutureExpiration", },
              tap.sample.Tap.Instrument.class,
              tap.sample.Tap.Instrument.Builder.class);
          internal_static_tap_sample_Exchange_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tap_sample_Exchange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_sample_Exchange_descriptor,
              new java.lang.String[] { "Mic", },
              tap.sample.Tap.Exchange.class,
              tap.sample.Tap.Exchange.Builder.class);
          internal_static_tap_sample_Currency_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_tap_sample_Currency_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_sample_Currency_descriptor,
              new java.lang.String[] { "Currency", },
              tap.sample.Tap.Currency.class,
              tap.sample.Tap.Currency.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
