// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tapfile.proto

package tap.formats.tapproto;

public final class Tapfile {
  private Tapfile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IndexEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes first_key = 1;
    boolean hasFirstKey();
    com.google.protobuf.ByteString getFirstKey();
    
    // optional uint64 data_offset = 2;
    boolean hasDataOffset();
    long getDataOffset();
    
    // optional uint64 data_bytes = 3;
    boolean hasDataBytes();
    long getDataBytes();
    
    // optional uint32 message_count = 6;
    boolean hasMessageCount();
    int getMessageCount();
  }
  public static final class IndexEntry extends
      com.google.protobuf.GeneratedMessage
      implements IndexEntryOrBuilder {
    // Use IndexEntry.newBuilder() to construct.
    private IndexEntry(Builder builder) {
      super(builder);
    }
    private IndexEntry(boolean noInit) {}
    
    private static final IndexEntry defaultInstance;
    public static IndexEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_IndexEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_IndexEntry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes first_key = 1;
    public static final int FIRST_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString firstKey_;
    public boolean hasFirstKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getFirstKey() {
      return firstKey_;
    }
    
    // optional uint64 data_offset = 2;
    public static final int DATA_OFFSET_FIELD_NUMBER = 2;
    private long dataOffset_;
    public boolean hasDataOffset() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getDataOffset() {
      return dataOffset_;
    }
    
    // optional uint64 data_bytes = 3;
    public static final int DATA_BYTES_FIELD_NUMBER = 3;
    private long dataBytes_;
    public boolean hasDataBytes() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getDataBytes() {
      return dataBytes_;
    }
    
    // optional uint32 message_count = 6;
    public static final int MESSAGE_COUNT_FIELD_NUMBER = 6;
    private int messageCount_;
    public boolean hasMessageCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getMessageCount() {
      return messageCount_;
    }
    
    private void initFields() {
      firstKey_ = com.google.protobuf.ByteString.EMPTY;
      dataOffset_ = 0L;
      dataBytes_ = 0L;
      messageCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, firstKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, dataOffset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, dataBytes_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(6, messageCount_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, firstKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, dataOffset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, dataBytes_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, messageCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.IndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.IndexEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.formats.tapproto.Tapfile.IndexEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_IndexEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_IndexEntry_fieldAccessorTable;
      }
      
      // Construct using tap.formats.tapproto.Tapfile.IndexEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        firstKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataOffset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        dataBytes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        messageCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.IndexEntry.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.IndexEntry getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.IndexEntry.getDefaultInstance();
      }
      
      public tap.formats.tapproto.Tapfile.IndexEntry build() {
        tap.formats.tapproto.Tapfile.IndexEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.formats.tapproto.Tapfile.IndexEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.formats.tapproto.Tapfile.IndexEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.formats.tapproto.Tapfile.IndexEntry buildPartial() {
        tap.formats.tapproto.Tapfile.IndexEntry result = new tap.formats.tapproto.Tapfile.IndexEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstKey_ = firstKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dataOffset_ = dataOffset_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataBytes_ = dataBytes_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageCount_ = messageCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.IndexEntry) {
          return mergeFrom((tap.formats.tapproto.Tapfile.IndexEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.IndexEntry other) {
        if (other == tap.formats.tapproto.Tapfile.IndexEntry.getDefaultInstance()) return this;
        if (other.hasFirstKey()) {
          setFirstKey(other.getFirstKey());
        }
        if (other.hasDataOffset()) {
          setDataOffset(other.getDataOffset());
        }
        if (other.hasDataBytes()) {
          setDataBytes(other.getDataBytes());
        }
        if (other.hasMessageCount()) {
          setMessageCount(other.getMessageCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              firstKey_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dataOffset_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              dataBytes_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              messageCount_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes first_key = 1;
      private com.google.protobuf.ByteString firstKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasFirstKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getFirstKey() {
        return firstKey_;
      }
      public Builder setFirstKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearFirstKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstKey_ = getDefaultInstance().getFirstKey();
        onChanged();
        return this;
      }
      
      // optional uint64 data_offset = 2;
      private long dataOffset_ ;
      public boolean hasDataOffset() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getDataOffset() {
        return dataOffset_;
      }
      public Builder setDataOffset(long value) {
        bitField0_ |= 0x00000002;
        dataOffset_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataOffset_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 data_bytes = 3;
      private long dataBytes_ ;
      public boolean hasDataBytes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getDataBytes() {
        return dataBytes_;
      }
      public Builder setDataBytes(long value) {
        bitField0_ |= 0x00000004;
        dataBytes_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataBytes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataBytes_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint32 message_count = 6;
      private int messageCount_ ;
      public boolean hasMessageCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMessageCount() {
        return messageCount_;
      }
      public Builder setMessageCount(int value) {
        bitField0_ |= 0x00000008;
        messageCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageCount_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.IndexEntry)
    }
    
    static {
      defaultInstance = new IndexEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.IndexEntry)
  }
  
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string copyright_notice = 100;
    boolean hasCopyrightNotice();
    String getCopyrightNotice();
    
    // optional uint32 partition_count = 101;
    boolean hasPartitionCount();
    int getPartitionCount();
    
    // optional uint32 partition_number = 102;
    boolean hasPartitionNumber();
    int getPartitionNumber();
    
    // optional string initial_pipe_name = 103;
    boolean hasInitialPipeName();
    String getInitialPipeName();
    
    // optional string message_name = 104;
    boolean hasMessageName();
    String getMessageName();
    
    // optional string key_descriptor = 105;
    boolean hasKeyDescriptor();
    String getKeyDescriptor();
    
    // optional uint64 target_decomp_size = 106;
    boolean hasTargetDecompSize();
    long getTargetDecompSize();
    
    // optional uint64 index_offset = 200;
    boolean hasIndexOffset();
    long getIndexOffset();
    
    // optional uint64 index_bytes = 201;
    boolean hasIndexBytes();
    long getIndexBytes();
    
    // optional bytes first_key = 202;
    boolean hasFirstKey();
    com.google.protobuf.ByteString getFirstKey();
    
    // optional bytes last_key = 203;
    boolean hasLastKey();
    com.google.protobuf.ByteString getLastKey();
    
    // optional uint64 message_count = 204;
    boolean hasMessageCount();
    long getMessageCount();
    
    // optional uint64 data_block_count = 205;
    boolean hasDataBlockCount();
    long getDataBlockCount();
    
    // optional uint64 uncompressed_bytes = 206;
    boolean hasUncompressedBytes();
    long getUncompressedBytes();
    
    // optional uint64 max_decomp_size = 207;
    boolean hasMaxDecompSize();
    long getMaxDecompSize();
    
    // repeated bytes format_descriptor = 301;
    java.util.List<com.google.protobuf.ByteString> getFormatDescriptorList();
    int getFormatDescriptorCount();
    com.google.protobuf.ByteString getFormatDescriptor(int index);
    
    // optional uint32 metadata_count = 302;
    boolean hasMetadataCount();
    int getMetadataCount();
  }
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(Builder builder) {
      super(builder);
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Header_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string copyright_notice = 100;
    public static final int COPYRIGHT_NOTICE_FIELD_NUMBER = 100;
    private java.lang.Object copyrightNotice_;
    public boolean hasCopyrightNotice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCopyrightNotice() {
      java.lang.Object ref = copyrightNotice_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          copyrightNotice_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCopyrightNoticeBytes() {
      java.lang.Object ref = copyrightNotice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        copyrightNotice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 partition_count = 101;
    public static final int PARTITION_COUNT_FIELD_NUMBER = 101;
    private int partitionCount_;
    public boolean hasPartitionCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPartitionCount() {
      return partitionCount_;
    }
    
    // optional uint32 partition_number = 102;
    public static final int PARTITION_NUMBER_FIELD_NUMBER = 102;
    private int partitionNumber_;
    public boolean hasPartitionNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPartitionNumber() {
      return partitionNumber_;
    }
    
    // optional string initial_pipe_name = 103;
    public static final int INITIAL_PIPE_NAME_FIELD_NUMBER = 103;
    private java.lang.Object initialPipeName_;
    public boolean hasInitialPipeName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getInitialPipeName() {
      java.lang.Object ref = initialPipeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          initialPipeName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInitialPipeNameBytes() {
      java.lang.Object ref = initialPipeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        initialPipeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string message_name = 104;
    public static final int MESSAGE_NAME_FIELD_NUMBER = 104;
    private java.lang.Object messageName_;
    public boolean hasMessageName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getMessageName() {
      java.lang.Object ref = messageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          messageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageNameBytes() {
      java.lang.Object ref = messageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        messageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string key_descriptor = 105;
    public static final int KEY_DESCRIPTOR_FIELD_NUMBER = 105;
    private java.lang.Object keyDescriptor_;
    public boolean hasKeyDescriptor() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getKeyDescriptor() {
      java.lang.Object ref = keyDescriptor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          keyDescriptor_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyDescriptorBytes() {
      java.lang.Object ref = keyDescriptor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        keyDescriptor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint64 target_decomp_size = 106;
    public static final int TARGET_DECOMP_SIZE_FIELD_NUMBER = 106;
    private long targetDecompSize_;
    public boolean hasTargetDecompSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getTargetDecompSize() {
      return targetDecompSize_;
    }
    
    // optional uint64 index_offset = 200;
    public static final int INDEX_OFFSET_FIELD_NUMBER = 200;
    private long indexOffset_;
    public boolean hasIndexOffset() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getIndexOffset() {
      return indexOffset_;
    }
    
    // optional uint64 index_bytes = 201;
    public static final int INDEX_BYTES_FIELD_NUMBER = 201;
    private long indexBytes_;
    public boolean hasIndexBytes() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getIndexBytes() {
      return indexBytes_;
    }
    
    // optional bytes first_key = 202;
    public static final int FIRST_KEY_FIELD_NUMBER = 202;
    private com.google.protobuf.ByteString firstKey_;
    public boolean hasFirstKey() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public com.google.protobuf.ByteString getFirstKey() {
      return firstKey_;
    }
    
    // optional bytes last_key = 203;
    public static final int LAST_KEY_FIELD_NUMBER = 203;
    private com.google.protobuf.ByteString lastKey_;
    public boolean hasLastKey() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public com.google.protobuf.ByteString getLastKey() {
      return lastKey_;
    }
    
    // optional uint64 message_count = 204;
    public static final int MESSAGE_COUNT_FIELD_NUMBER = 204;
    private long messageCount_;
    public boolean hasMessageCount() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public long getMessageCount() {
      return messageCount_;
    }
    
    // optional uint64 data_block_count = 205;
    public static final int DATA_BLOCK_COUNT_FIELD_NUMBER = 205;
    private long dataBlockCount_;
    public boolean hasDataBlockCount() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public long getDataBlockCount() {
      return dataBlockCount_;
    }
    
    // optional uint64 uncompressed_bytes = 206;
    public static final int UNCOMPRESSED_BYTES_FIELD_NUMBER = 206;
    private long uncompressedBytes_;
    public boolean hasUncompressedBytes() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public long getUncompressedBytes() {
      return uncompressedBytes_;
    }
    
    // optional uint64 max_decomp_size = 207;
    public static final int MAX_DECOMP_SIZE_FIELD_NUMBER = 207;
    private long maxDecompSize_;
    public boolean hasMaxDecompSize() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public long getMaxDecompSize() {
      return maxDecompSize_;
    }
    
    // repeated bytes format_descriptor = 301;
    public static final int FORMAT_DESCRIPTOR_FIELD_NUMBER = 301;
    private java.util.List<com.google.protobuf.ByteString> formatDescriptor_;
    public java.util.List<com.google.protobuf.ByteString>
        getFormatDescriptorList() {
      return formatDescriptor_;
    }
    public int getFormatDescriptorCount() {
      return formatDescriptor_.size();
    }
    public com.google.protobuf.ByteString getFormatDescriptor(int index) {
      return formatDescriptor_.get(index);
    }
    
    // optional uint32 metadata_count = 302;
    public static final int METADATA_COUNT_FIELD_NUMBER = 302;
    private int metadataCount_;
    public boolean hasMetadataCount() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public int getMetadataCount() {
      return metadataCount_;
    }
    
    private void initFields() {
      copyrightNotice_ = "";
      partitionCount_ = 0;
      partitionNumber_ = 0;
      initialPipeName_ = "";
      messageName_ = "";
      keyDescriptor_ = "";
      targetDecompSize_ = 0L;
      indexOffset_ = 0L;
      indexBytes_ = 0L;
      firstKey_ = com.google.protobuf.ByteString.EMPTY;
      lastKey_ = com.google.protobuf.ByteString.EMPTY;
      messageCount_ = 0L;
      dataBlockCount_ = 0L;
      uncompressedBytes_ = 0L;
      maxDecompSize_ = 0L;
      formatDescriptor_ = java.util.Collections.emptyList();;
      metadataCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(100, getCopyrightNoticeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(101, partitionCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(102, partitionNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(103, getInitialPipeNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(104, getMessageNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(105, getKeyDescriptorBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(106, targetDecompSize_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(200, indexOffset_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(201, indexBytes_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(202, firstKey_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(203, lastKey_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(204, messageCount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt64(205, dataBlockCount_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeUInt64(206, uncompressedBytes_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeUInt64(207, maxDecompSize_);
      }
      for (int i = 0; i < formatDescriptor_.size(); i++) {
        output.writeBytes(301, formatDescriptor_.get(i));
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeUInt32(302, metadataCount_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(100, getCopyrightNoticeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(101, partitionCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(102, partitionNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(103, getInitialPipeNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(104, getMessageNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(105, getKeyDescriptorBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(106, targetDecompSize_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(200, indexOffset_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(201, indexBytes_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(202, firstKey_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(203, lastKey_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(204, messageCount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(205, dataBlockCount_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(206, uncompressedBytes_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(207, maxDecompSize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < formatDescriptor_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(formatDescriptor_.get(i));
        }
        size += dataSize;
        size += 2 * getFormatDescriptorList().size();
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(302, metadataCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.formats.tapproto.Tapfile.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Header_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Header_fieldAccessorTable;
      }
      
      // Construct using tap.formats.tapproto.Tapfile.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        copyrightNotice_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        partitionCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        partitionNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        initialPipeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        messageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        keyDescriptor_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        targetDecompSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        indexOffset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        indexBytes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        firstKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        lastKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        messageCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        dataBlockCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        uncompressedBytes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        maxDecompSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        formatDescriptor_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00008000);
        metadataCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.Header.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.Header getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.Header.getDefaultInstance();
      }
      
      public tap.formats.tapproto.Tapfile.Header build() {
        tap.formats.tapproto.Tapfile.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.formats.tapproto.Tapfile.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.formats.tapproto.Tapfile.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.formats.tapproto.Tapfile.Header buildPartial() {
        tap.formats.tapproto.Tapfile.Header result = new tap.formats.tapproto.Tapfile.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.copyrightNotice_ = copyrightNotice_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.partitionCount_ = partitionCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.partitionNumber_ = partitionNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.initialPipeName_ = initialPipeName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageName_ = messageName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.keyDescriptor_ = keyDescriptor_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.targetDecompSize_ = targetDecompSize_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.indexOffset_ = indexOffset_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.indexBytes_ = indexBytes_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.firstKey_ = firstKey_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.lastKey_ = lastKey_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.messageCount_ = messageCount_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.dataBlockCount_ = dataBlockCount_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.uncompressedBytes_ = uncompressedBytes_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.maxDecompSize_ = maxDecompSize_;
        if (((bitField0_ & 0x00008000) == 0x00008000)) {
          formatDescriptor_ = java.util.Collections.unmodifiableList(formatDescriptor_);
          bitField0_ = (bitField0_ & ~0x00008000);
        }
        result.formatDescriptor_ = formatDescriptor_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.metadataCount_ = metadataCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.Header) {
          return mergeFrom((tap.formats.tapproto.Tapfile.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.Header other) {
        if (other == tap.formats.tapproto.Tapfile.Header.getDefaultInstance()) return this;
        if (other.hasCopyrightNotice()) {
          setCopyrightNotice(other.getCopyrightNotice());
        }
        if (other.hasPartitionCount()) {
          setPartitionCount(other.getPartitionCount());
        }
        if (other.hasPartitionNumber()) {
          setPartitionNumber(other.getPartitionNumber());
        }
        if (other.hasInitialPipeName()) {
          setInitialPipeName(other.getInitialPipeName());
        }
        if (other.hasMessageName()) {
          setMessageName(other.getMessageName());
        }
        if (other.hasKeyDescriptor()) {
          setKeyDescriptor(other.getKeyDescriptor());
        }
        if (other.hasTargetDecompSize()) {
          setTargetDecompSize(other.getTargetDecompSize());
        }
        if (other.hasIndexOffset()) {
          setIndexOffset(other.getIndexOffset());
        }
        if (other.hasIndexBytes()) {
          setIndexBytes(other.getIndexBytes());
        }
        if (other.hasFirstKey()) {
          setFirstKey(other.getFirstKey());
        }
        if (other.hasLastKey()) {
          setLastKey(other.getLastKey());
        }
        if (other.hasMessageCount()) {
          setMessageCount(other.getMessageCount());
        }
        if (other.hasDataBlockCount()) {
          setDataBlockCount(other.getDataBlockCount());
        }
        if (other.hasUncompressedBytes()) {
          setUncompressedBytes(other.getUncompressedBytes());
        }
        if (other.hasMaxDecompSize()) {
          setMaxDecompSize(other.getMaxDecompSize());
        }
        if (!other.formatDescriptor_.isEmpty()) {
          if (formatDescriptor_.isEmpty()) {
            formatDescriptor_ = other.formatDescriptor_;
            bitField0_ = (bitField0_ & ~0x00008000);
          } else {
            ensureFormatDescriptorIsMutable();
            formatDescriptor_.addAll(other.formatDescriptor_);
          }
          onChanged();
        }
        if (other.hasMetadataCount()) {
          setMetadataCount(other.getMetadataCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 802: {
              bitField0_ |= 0x00000001;
              copyrightNotice_ = input.readBytes();
              break;
            }
            case 808: {
              bitField0_ |= 0x00000002;
              partitionCount_ = input.readUInt32();
              break;
            }
            case 816: {
              bitField0_ |= 0x00000004;
              partitionNumber_ = input.readUInt32();
              break;
            }
            case 826: {
              bitField0_ |= 0x00000008;
              initialPipeName_ = input.readBytes();
              break;
            }
            case 834: {
              bitField0_ |= 0x00000010;
              messageName_ = input.readBytes();
              break;
            }
            case 842: {
              bitField0_ |= 0x00000020;
              keyDescriptor_ = input.readBytes();
              break;
            }
            case 848: {
              bitField0_ |= 0x00000040;
              targetDecompSize_ = input.readUInt64();
              break;
            }
            case 1600: {
              bitField0_ |= 0x00000080;
              indexOffset_ = input.readUInt64();
              break;
            }
            case 1608: {
              bitField0_ |= 0x00000100;
              indexBytes_ = input.readUInt64();
              break;
            }
            case 1618: {
              bitField0_ |= 0x00000200;
              firstKey_ = input.readBytes();
              break;
            }
            case 1626: {
              bitField0_ |= 0x00000400;
              lastKey_ = input.readBytes();
              break;
            }
            case 1632: {
              bitField0_ |= 0x00000800;
              messageCount_ = input.readUInt64();
              break;
            }
            case 1640: {
              bitField0_ |= 0x00001000;
              dataBlockCount_ = input.readUInt64();
              break;
            }
            case 1648: {
              bitField0_ |= 0x00002000;
              uncompressedBytes_ = input.readUInt64();
              break;
            }
            case 1656: {
              bitField0_ |= 0x00004000;
              maxDecompSize_ = input.readUInt64();
              break;
            }
            case 2410: {
              ensureFormatDescriptorIsMutable();
              formatDescriptor_.add(input.readBytes());
              break;
            }
            case 2416: {
              bitField0_ |= 0x00010000;
              metadataCount_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string copyright_notice = 100;
      private java.lang.Object copyrightNotice_ = "";
      public boolean hasCopyrightNotice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCopyrightNotice() {
        java.lang.Object ref = copyrightNotice_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          copyrightNotice_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCopyrightNotice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        copyrightNotice_ = value;
        onChanged();
        return this;
      }
      public Builder clearCopyrightNotice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        copyrightNotice_ = getDefaultInstance().getCopyrightNotice();
        onChanged();
        return this;
      }
      void setCopyrightNotice(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        copyrightNotice_ = value;
        onChanged();
      }
      
      // optional uint32 partition_count = 101;
      private int partitionCount_ ;
      public boolean hasPartitionCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPartitionCount() {
        return partitionCount_;
      }
      public Builder setPartitionCount(int value) {
        bitField0_ |= 0x00000002;
        partitionCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearPartitionCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        partitionCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 partition_number = 102;
      private int partitionNumber_ ;
      public boolean hasPartitionNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPartitionNumber() {
        return partitionNumber_;
      }
      public Builder setPartitionNumber(int value) {
        bitField0_ |= 0x00000004;
        partitionNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearPartitionNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        partitionNumber_ = 0;
        onChanged();
        return this;
      }
      
      // optional string initial_pipe_name = 103;
      private java.lang.Object initialPipeName_ = "";
      public boolean hasInitialPipeName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getInitialPipeName() {
        java.lang.Object ref = initialPipeName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          initialPipeName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInitialPipeName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        initialPipeName_ = value;
        onChanged();
        return this;
      }
      public Builder clearInitialPipeName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        initialPipeName_ = getDefaultInstance().getInitialPipeName();
        onChanged();
        return this;
      }
      void setInitialPipeName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        initialPipeName_ = value;
        onChanged();
      }
      
      // optional string message_name = 104;
      private java.lang.Object messageName_ = "";
      public boolean hasMessageName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMessageName() {
        java.lang.Object ref = messageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          messageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        messageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageName_ = getDefaultInstance().getMessageName();
        onChanged();
        return this;
      }
      void setMessageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        messageName_ = value;
        onChanged();
      }
      
      // optional string key_descriptor = 105;
      private java.lang.Object keyDescriptor_ = "";
      public boolean hasKeyDescriptor() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getKeyDescriptor() {
        java.lang.Object ref = keyDescriptor_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          keyDescriptor_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKeyDescriptor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        keyDescriptor_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyDescriptor() {
        bitField0_ = (bitField0_ & ~0x00000020);
        keyDescriptor_ = getDefaultInstance().getKeyDescriptor();
        onChanged();
        return this;
      }
      void setKeyDescriptor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        keyDescriptor_ = value;
        onChanged();
      }
      
      // optional uint64 target_decomp_size = 106;
      private long targetDecompSize_ ;
      public boolean hasTargetDecompSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getTargetDecompSize() {
        return targetDecompSize_;
      }
      public Builder setTargetDecompSize(long value) {
        bitField0_ |= 0x00000040;
        targetDecompSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetDecompSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        targetDecompSize_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 index_offset = 200;
      private long indexOffset_ ;
      public boolean hasIndexOffset() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getIndexOffset() {
        return indexOffset_;
      }
      public Builder setIndexOffset(long value) {
        bitField0_ |= 0x00000080;
        indexOffset_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndexOffset() {
        bitField0_ = (bitField0_ & ~0x00000080);
        indexOffset_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 index_bytes = 201;
      private long indexBytes_ ;
      public boolean hasIndexBytes() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getIndexBytes() {
        return indexBytes_;
      }
      public Builder setIndexBytes(long value) {
        bitField0_ |= 0x00000100;
        indexBytes_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndexBytes() {
        bitField0_ = (bitField0_ & ~0x00000100);
        indexBytes_ = 0L;
        onChanged();
        return this;
      }
      
      // optional bytes first_key = 202;
      private com.google.protobuf.ByteString firstKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasFirstKey() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public com.google.protobuf.ByteString getFirstKey() {
        return firstKey_;
      }
      public Builder setFirstKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        firstKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearFirstKey() {
        bitField0_ = (bitField0_ & ~0x00000200);
        firstKey_ = getDefaultInstance().getFirstKey();
        onChanged();
        return this;
      }
      
      // optional bytes last_key = 203;
      private com.google.protobuf.ByteString lastKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasLastKey() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public com.google.protobuf.ByteString getLastKey() {
        return lastKey_;
      }
      public Builder setLastKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        lastKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastKey() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lastKey_ = getDefaultInstance().getLastKey();
        onChanged();
        return this;
      }
      
      // optional uint64 message_count = 204;
      private long messageCount_ ;
      public boolean hasMessageCount() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public long getMessageCount() {
        return messageCount_;
      }
      public Builder setMessageCount(long value) {
        bitField0_ |= 0x00000800;
        messageCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageCount() {
        bitField0_ = (bitField0_ & ~0x00000800);
        messageCount_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 data_block_count = 205;
      private long dataBlockCount_ ;
      public boolean hasDataBlockCount() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public long getDataBlockCount() {
        return dataBlockCount_;
      }
      public Builder setDataBlockCount(long value) {
        bitField0_ |= 0x00001000;
        dataBlockCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataBlockCount() {
        bitField0_ = (bitField0_ & ~0x00001000);
        dataBlockCount_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 uncompressed_bytes = 206;
      private long uncompressedBytes_ ;
      public boolean hasUncompressedBytes() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public long getUncompressedBytes() {
        return uncompressedBytes_;
      }
      public Builder setUncompressedBytes(long value) {
        bitField0_ |= 0x00002000;
        uncompressedBytes_ = value;
        onChanged();
        return this;
      }
      public Builder clearUncompressedBytes() {
        bitField0_ = (bitField0_ & ~0x00002000);
        uncompressedBytes_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 max_decomp_size = 207;
      private long maxDecompSize_ ;
      public boolean hasMaxDecompSize() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public long getMaxDecompSize() {
        return maxDecompSize_;
      }
      public Builder setMaxDecompSize(long value) {
        bitField0_ |= 0x00004000;
        maxDecompSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxDecompSize() {
        bitField0_ = (bitField0_ & ~0x00004000);
        maxDecompSize_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated bytes format_descriptor = 301;
      private java.util.List<com.google.protobuf.ByteString> formatDescriptor_ = java.util.Collections.emptyList();;
      private void ensureFormatDescriptorIsMutable() {
        if (!((bitField0_ & 0x00008000) == 0x00008000)) {
          formatDescriptor_ = new java.util.ArrayList<com.google.protobuf.ByteString>(formatDescriptor_);
          bitField0_ |= 0x00008000;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getFormatDescriptorList() {
        return java.util.Collections.unmodifiableList(formatDescriptor_);
      }
      public int getFormatDescriptorCount() {
        return formatDescriptor_.size();
      }
      public com.google.protobuf.ByteString getFormatDescriptor(int index) {
        return formatDescriptor_.get(index);
      }
      public Builder setFormatDescriptor(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFormatDescriptorIsMutable();
        formatDescriptor_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFormatDescriptor(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFormatDescriptorIsMutable();
        formatDescriptor_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFormatDescriptor(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureFormatDescriptorIsMutable();
        super.addAll(values, formatDescriptor_);
        onChanged();
        return this;
      }
      public Builder clearFormatDescriptor() {
        formatDescriptor_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
        return this;
      }
      
      // optional uint32 metadata_count = 302;
      private int metadataCount_ ;
      public boolean hasMetadataCount() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public int getMetadataCount() {
        return metadataCount_;
      }
      public Builder setMetadataCount(int value) {
        bitField0_ |= 0x00010000;
        metadataCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearMetadataCount() {
        bitField0_ = (bitField0_ & ~0x00010000);
        metadataCount_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.Header)
    }
    
    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.Header)
  }
  
  public interface MetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional string string_value = 2;
    boolean hasStringValue();
    String getStringValue();
    
    // optional uint64 integer_value = 3;
    boolean hasIntegerValue();
    long getIntegerValue();
    
    // optional double double_value = 4;
    boolean hasDoubleValue();
    double getDoubleValue();
    
    // optional bytes bytes_value = 5;
    boolean hasBytesValue();
    com.google.protobuf.ByteString getBytesValue();
  }
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessage
      implements MetadataOrBuilder {
    // Use Metadata.newBuilder() to construct.
    private Metadata(Builder builder) {
      super(builder);
    }
    private Metadata(boolean noInit) {}
    
    private static final Metadata defaultInstance;
    public static Metadata getDefaultInstance() {
      return defaultInstance;
    }
    
    public Metadata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Metadata_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string string_value = 2;
    public static final int STRING_VALUE_FIELD_NUMBER = 2;
    private java.lang.Object stringValue_;
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stringValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint64 integer_value = 3;
    public static final int INTEGER_VALUE_FIELD_NUMBER = 3;
    private long integerValue_;
    public boolean hasIntegerValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getIntegerValue() {
      return integerValue_;
    }
    
    // optional double double_value = 4;
    public static final int DOUBLE_VALUE_FIELD_NUMBER = 4;
    private double doubleValue_;
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getDoubleValue() {
      return doubleValue_;
    }
    
    // optional bytes bytes_value = 5;
    public static final int BYTES_VALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString bytesValue_;
    public boolean hasBytesValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getBytesValue() {
      return bytesValue_;
    }
    
    private void initFields() {
      key_ = "";
      stringValue_ = "";
      integerValue_ = 0L;
      doubleValue_ = 0D;
      bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, integerValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, doubleValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, bytesValue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, integerValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, doubleValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, bytesValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.Metadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tap.formats.tapproto.Tapfile.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Metadata_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable;
      }
      
      // Construct using tap.formats.tapproto.Tapfile.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        integerValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        bytesValue_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.Metadata.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.Metadata getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.Metadata.getDefaultInstance();
      }
      
      public tap.formats.tapproto.Tapfile.Metadata build() {
        tap.formats.tapproto.Tapfile.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tap.formats.tapproto.Tapfile.Metadata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tap.formats.tapproto.Tapfile.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tap.formats.tapproto.Tapfile.Metadata buildPartial() {
        tap.formats.tapproto.Tapfile.Metadata result = new tap.formats.tapproto.Tapfile.Metadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.integerValue_ = integerValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.doubleValue_ = doubleValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bytesValue_ = bytesValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.Metadata) {
          return mergeFrom((tap.formats.tapproto.Tapfile.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.Metadata other) {
        if (other == tap.formats.tapproto.Tapfile.Metadata.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasStringValue()) {
          setStringValue(other.getStringValue());
        }
        if (other.hasIntegerValue()) {
          setIntegerValue(other.getIntegerValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasBytesValue()) {
          setBytesValue(other.getBytesValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              stringValue_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              integerValue_ = input.readUInt64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              doubleValue_ = input.readDouble();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              bytesValue_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional string string_value = 2;
      private java.lang.Object stringValue_ = "";
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStringValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stringValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      void setStringValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        stringValue_ = value;
        onChanged();
      }
      
      // optional uint64 integer_value = 3;
      private long integerValue_ ;
      public boolean hasIntegerValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getIntegerValue() {
        return integerValue_;
      }
      public Builder setIntegerValue(long value) {
        bitField0_ |= 0x00000004;
        integerValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearIntegerValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        integerValue_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double double_value = 4;
      private double doubleValue_ ;
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getDoubleValue() {
        return doubleValue_;
      }
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000008;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }
      
      // optional bytes bytes_value = 5;
      private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBytesValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getBytesValue() {
        return bytesValue_;
      }
      public Builder setBytesValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bytesValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearBytesValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bytesValue_ = getDefaultInstance().getBytesValue();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.Metadata)
    }
    
    static {
      defaultInstance = new Metadata(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.Metadata)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_IndexEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_IndexEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_Metadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtapfile.proto\022\024tap.formats.tapproto\"_\n" +
      "\nIndexEntry\022\021\n\tfirst_key\030\001 \001(\014\022\023\n\013data_o" +
      "ffset\030\002 \001(\004\022\022\n\ndata_bytes\030\003 \001(\004\022\025\n\rmessa" +
      "ge_count\030\006 \001(\r\"\255\003\n\006Header\022\030\n\020copyright_n" +
      "otice\030d \001(\t\022\027\n\017partition_count\030e \001(\r\022\030\n\020" +
      "partition_number\030f \001(\r\022\031\n\021initial_pipe_n" +
      "ame\030g \001(\t\022\024\n\014message_name\030h \001(\t\022\026\n\016key_d" +
      "escriptor\030i \001(\t\022\032\n\022target_decomp_size\030j " +
      "\001(\004\022\025\n\014index_offset\030\310\001 \001(\004\022\024\n\013index_byte" +
      "s\030\311\001 \001(\004\022\022\n\tfirst_key\030\312\001 \001(\014\022\021\n\010last_key",
      "\030\313\001 \001(\014\022\026\n\rmessage_count\030\314\001 \001(\004\022\031\n\020data_" +
      "block_count\030\315\001 \001(\004\022\033\n\022uncompressed_bytes" +
      "\030\316\001 \001(\004\022\030\n\017max_decomp_size\030\317\001 \001(\004\022\032\n\021for" +
      "mat_descriptor\030\255\002 \003(\014\022\027\n\016metadata_count\030" +
      "\256\002 \001(\r\"o\n\010Metadata\022\013\n\003key\030\001 \001(\t\022\024\n\014strin" +
      "g_value\030\002 \001(\t\022\025\n\rinteger_value\030\003 \001(\004\022\024\n\014" +
      "double_value\030\004 \001(\001\022\023\n\013bytes_value\030\005 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tap_formats_tapproto_IndexEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tap_formats_tapproto_IndexEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_IndexEntry_descriptor,
              new java.lang.String[] { "FirstKey", "DataOffset", "DataBytes", "MessageCount", },
              tap.formats.tapproto.Tapfile.IndexEntry.class,
              tap.formats.tapproto.Tapfile.IndexEntry.Builder.class);
          internal_static_tap_formats_tapproto_Header_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tap_formats_tapproto_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_Header_descriptor,
              new java.lang.String[] { "CopyrightNotice", "PartitionCount", "PartitionNumber", "InitialPipeName", "MessageName", "KeyDescriptor", "TargetDecompSize", "IndexOffset", "IndexBytes", "FirstKey", "LastKey", "MessageCount", "DataBlockCount", "UncompressedBytes", "MaxDecompSize", "FormatDescriptor", "MetadataCount", },
              tap.formats.tapproto.Tapfile.Header.class,
              tap.formats.tapproto.Tapfile.Header.Builder.class);
          internal_static_tap_formats_tapproto_Metadata_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_Metadata_descriptor,
              new java.lang.String[] { "Key", "StringValue", "IntegerValue", "DoubleValue", "BytesValue", },
              tap.formats.tapproto.Tapfile.Metadata.class,
              tap.formats.tapproto.Tapfile.Metadata.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
