// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tapfile.proto

package tap.formats.tapproto;

public final class Tapfile {
  private Tapfile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LowerIndexEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use LowerIndexEntry.newBuilder() to construct.
    private LowerIndexEntry() {
      initFields();
    }
    private LowerIndexEntry(boolean noInit) {}
    
    private static final LowerIndexEntry defaultInstance;
    public static LowerIndexEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public LowerIndexEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_LowerIndexEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_LowerIndexEntry_fieldAccessorTable;
    }
    
    // optional bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // optional uint32 message_size = 2;
    public static final int MESSAGE_SIZE_FIELD_NUMBER = 2;
    private boolean hasMessageSize;
    private int messageSize_ = 0;
    public boolean hasMessageSize() { return hasMessageSize; }
    public int getMessageSize() { return messageSize_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      if (hasMessageSize()) {
        output.writeUInt32(2, getMessageSize());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      if (hasMessageSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getMessageSize());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.LowerIndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.LowerIndexEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private tap.formats.tapproto.Tapfile.LowerIndexEntry result;
      
      // Construct using tap.formats.tapproto.Tapfile.LowerIndexEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new tap.formats.tapproto.Tapfile.LowerIndexEntry();
        return builder;
      }
      
      protected tap.formats.tapproto.Tapfile.LowerIndexEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new tap.formats.tapproto.Tapfile.LowerIndexEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.LowerIndexEntry.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.LowerIndexEntry getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.LowerIndexEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public tap.formats.tapproto.Tapfile.LowerIndexEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private tap.formats.tapproto.Tapfile.LowerIndexEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public tap.formats.tapproto.Tapfile.LowerIndexEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        tap.formats.tapproto.Tapfile.LowerIndexEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.LowerIndexEntry) {
          return mergeFrom((tap.formats.tapproto.Tapfile.LowerIndexEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.LowerIndexEntry other) {
        if (other == tap.formats.tapproto.Tapfile.LowerIndexEntry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasMessageSize()) {
          setMessageSize(other.getMessageSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 16: {
              setMessageSize(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional uint32 message_size = 2;
      public boolean hasMessageSize() {
        return result.hasMessageSize();
      }
      public int getMessageSize() {
        return result.getMessageSize();
      }
      public Builder setMessageSize(int value) {
        result.hasMessageSize = true;
        result.messageSize_ = value;
        return this;
      }
      public Builder clearMessageSize() {
        result.hasMessageSize = false;
        result.messageSize_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.LowerIndexEntry)
    }
    
    static {
      defaultInstance = new LowerIndexEntry(true);
      tap.formats.tapproto.Tapfile.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.LowerIndexEntry)
  }
  
  public static final class UpperIndexEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use UpperIndexEntry.newBuilder() to construct.
    private UpperIndexEntry() {
      initFields();
    }
    private UpperIndexEntry(boolean noInit) {}
    
    private static final UpperIndexEntry defaultInstance;
    public static UpperIndexEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public UpperIndexEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_UpperIndexEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_UpperIndexEntry_fieldAccessorTable;
    }
    
    // optional bytes first_key = 1;
    public static final int FIRST_KEY_FIELD_NUMBER = 1;
    private boolean hasFirstKey;
    private com.google.protobuf.ByteString firstKey_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasFirstKey() { return hasFirstKey; }
    public com.google.protobuf.ByteString getFirstKey() { return firstKey_; }
    
    // optional uint64 data_offset = 2;
    public static final int DATA_OFFSET_FIELD_NUMBER = 2;
    private boolean hasDataOffset;
    private long dataOffset_ = 0L;
    public boolean hasDataOffset() { return hasDataOffset; }
    public long getDataOffset() { return dataOffset_; }
    
    // optional uint64 data_bytes = 3;
    public static final int DATA_BYTES_FIELD_NUMBER = 3;
    private boolean hasDataBytes;
    private long dataBytes_ = 0L;
    public boolean hasDataBytes() { return hasDataBytes; }
    public long getDataBytes() { return dataBytes_; }
    
    // optional uint64 lower_index_offset = 4;
    public static final int LOWER_INDEX_OFFSET_FIELD_NUMBER = 4;
    private boolean hasLowerIndexOffset;
    private long lowerIndexOffset_ = 0L;
    public boolean hasLowerIndexOffset() { return hasLowerIndexOffset; }
    public long getLowerIndexOffset() { return lowerIndexOffset_; }
    
    // optional uint64 lower_index_bytes = 5;
    public static final int LOWER_INDEX_BYTES_FIELD_NUMBER = 5;
    private boolean hasLowerIndexBytes;
    private long lowerIndexBytes_ = 0L;
    public boolean hasLowerIndexBytes() { return hasLowerIndexBytes; }
    public long getLowerIndexBytes() { return lowerIndexBytes_; }
    
    // optional uint32 message_count = 6;
    public static final int MESSAGE_COUNT_FIELD_NUMBER = 6;
    private boolean hasMessageCount;
    private int messageCount_ = 0;
    public boolean hasMessageCount() { return hasMessageCount; }
    public int getMessageCount() { return messageCount_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFirstKey()) {
        output.writeBytes(1, getFirstKey());
      }
      if (hasDataOffset()) {
        output.writeUInt64(2, getDataOffset());
      }
      if (hasDataBytes()) {
        output.writeUInt64(3, getDataBytes());
      }
      if (hasLowerIndexOffset()) {
        output.writeUInt64(4, getLowerIndexOffset());
      }
      if (hasLowerIndexBytes()) {
        output.writeUInt64(5, getLowerIndexBytes());
      }
      if (hasMessageCount()) {
        output.writeUInt32(6, getMessageCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFirstKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFirstKey());
      }
      if (hasDataOffset()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, getDataOffset());
      }
      if (hasDataBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getDataBytes());
      }
      if (hasLowerIndexOffset()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, getLowerIndexOffset());
      }
      if (hasLowerIndexBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, getLowerIndexBytes());
      }
      if (hasMessageCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getMessageCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.UpperIndexEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.UpperIndexEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private tap.formats.tapproto.Tapfile.UpperIndexEntry result;
      
      // Construct using tap.formats.tapproto.Tapfile.UpperIndexEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new tap.formats.tapproto.Tapfile.UpperIndexEntry();
        return builder;
      }
      
      protected tap.formats.tapproto.Tapfile.UpperIndexEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new tap.formats.tapproto.Tapfile.UpperIndexEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.UpperIndexEntry.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.UpperIndexEntry getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.UpperIndexEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public tap.formats.tapproto.Tapfile.UpperIndexEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private tap.formats.tapproto.Tapfile.UpperIndexEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public tap.formats.tapproto.Tapfile.UpperIndexEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        tap.formats.tapproto.Tapfile.UpperIndexEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.UpperIndexEntry) {
          return mergeFrom((tap.formats.tapproto.Tapfile.UpperIndexEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.UpperIndexEntry other) {
        if (other == tap.formats.tapproto.Tapfile.UpperIndexEntry.getDefaultInstance()) return this;
        if (other.hasFirstKey()) {
          setFirstKey(other.getFirstKey());
        }
        if (other.hasDataOffset()) {
          setDataOffset(other.getDataOffset());
        }
        if (other.hasDataBytes()) {
          setDataBytes(other.getDataBytes());
        }
        if (other.hasLowerIndexOffset()) {
          setLowerIndexOffset(other.getLowerIndexOffset());
        }
        if (other.hasLowerIndexBytes()) {
          setLowerIndexBytes(other.getLowerIndexBytes());
        }
        if (other.hasMessageCount()) {
          setMessageCount(other.getMessageCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFirstKey(input.readBytes());
              break;
            }
            case 16: {
              setDataOffset(input.readUInt64());
              break;
            }
            case 24: {
              setDataBytes(input.readUInt64());
              break;
            }
            case 32: {
              setLowerIndexOffset(input.readUInt64());
              break;
            }
            case 40: {
              setLowerIndexBytes(input.readUInt64());
              break;
            }
            case 48: {
              setMessageCount(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional bytes first_key = 1;
      public boolean hasFirstKey() {
        return result.hasFirstKey();
      }
      public com.google.protobuf.ByteString getFirstKey() {
        return result.getFirstKey();
      }
      public Builder setFirstKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFirstKey = true;
        result.firstKey_ = value;
        return this;
      }
      public Builder clearFirstKey() {
        result.hasFirstKey = false;
        result.firstKey_ = getDefaultInstance().getFirstKey();
        return this;
      }
      
      // optional uint64 data_offset = 2;
      public boolean hasDataOffset() {
        return result.hasDataOffset();
      }
      public long getDataOffset() {
        return result.getDataOffset();
      }
      public Builder setDataOffset(long value) {
        result.hasDataOffset = true;
        result.dataOffset_ = value;
        return this;
      }
      public Builder clearDataOffset() {
        result.hasDataOffset = false;
        result.dataOffset_ = 0L;
        return this;
      }
      
      // optional uint64 data_bytes = 3;
      public boolean hasDataBytes() {
        return result.hasDataBytes();
      }
      public long getDataBytes() {
        return result.getDataBytes();
      }
      public Builder setDataBytes(long value) {
        result.hasDataBytes = true;
        result.dataBytes_ = value;
        return this;
      }
      public Builder clearDataBytes() {
        result.hasDataBytes = false;
        result.dataBytes_ = 0L;
        return this;
      }
      
      // optional uint64 lower_index_offset = 4;
      public boolean hasLowerIndexOffset() {
        return result.hasLowerIndexOffset();
      }
      public long getLowerIndexOffset() {
        return result.getLowerIndexOffset();
      }
      public Builder setLowerIndexOffset(long value) {
        result.hasLowerIndexOffset = true;
        result.lowerIndexOffset_ = value;
        return this;
      }
      public Builder clearLowerIndexOffset() {
        result.hasLowerIndexOffset = false;
        result.lowerIndexOffset_ = 0L;
        return this;
      }
      
      // optional uint64 lower_index_bytes = 5;
      public boolean hasLowerIndexBytes() {
        return result.hasLowerIndexBytes();
      }
      public long getLowerIndexBytes() {
        return result.getLowerIndexBytes();
      }
      public Builder setLowerIndexBytes(long value) {
        result.hasLowerIndexBytes = true;
        result.lowerIndexBytes_ = value;
        return this;
      }
      public Builder clearLowerIndexBytes() {
        result.hasLowerIndexBytes = false;
        result.lowerIndexBytes_ = 0L;
        return this;
      }
      
      // optional uint32 message_count = 6;
      public boolean hasMessageCount() {
        return result.hasMessageCount();
      }
      public int getMessageCount() {
        return result.getMessageCount();
      }
      public Builder setMessageCount(int value) {
        result.hasMessageCount = true;
        result.messageCount_ = value;
        return this;
      }
      public Builder clearMessageCount() {
        result.hasMessageCount = false;
        result.messageCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.UpperIndexEntry)
    }
    
    static {
      defaultInstance = new UpperIndexEntry(true);
      tap.formats.tapproto.Tapfile.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.UpperIndexEntry)
  }
  
  public static final class Header extends
      com.google.protobuf.GeneratedMessage {
    // Use Header.newBuilder() to construct.
    private Header() {
      initFields();
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Header_fieldAccessorTable;
    }
    
    // optional string copyright_notice = 100;
    public static final int COPYRIGHT_NOTICE_FIELD_NUMBER = 100;
    private boolean hasCopyrightNotice;
    private java.lang.String copyrightNotice_ = "";
    public boolean hasCopyrightNotice() { return hasCopyrightNotice; }
    public java.lang.String getCopyrightNotice() { return copyrightNotice_; }
    
    // optional uint32 partition_count = 101;
    public static final int PARTITION_COUNT_FIELD_NUMBER = 101;
    private boolean hasPartitionCount;
    private int partitionCount_ = 0;
    public boolean hasPartitionCount() { return hasPartitionCount; }
    public int getPartitionCount() { return partitionCount_; }
    
    // optional uint32 partition_number = 102;
    public static final int PARTITION_NUMBER_FIELD_NUMBER = 102;
    private boolean hasPartitionNumber;
    private int partitionNumber_ = 0;
    public boolean hasPartitionNumber() { return hasPartitionNumber; }
    public int getPartitionNumber() { return partitionNumber_; }
    
    // optional string initial_pipe_name = 103;
    public static final int INITIAL_PIPE_NAME_FIELD_NUMBER = 103;
    private boolean hasInitialPipeName;
    private java.lang.String initialPipeName_ = "";
    public boolean hasInitialPipeName() { return hasInitialPipeName; }
    public java.lang.String getInitialPipeName() { return initialPipeName_; }
    
    // optional string message_name = 104;
    public static final int MESSAGE_NAME_FIELD_NUMBER = 104;
    private boolean hasMessageName;
    private java.lang.String messageName_ = "";
    public boolean hasMessageName() { return hasMessageName; }
    public java.lang.String getMessageName() { return messageName_; }
    
    // optional string key_descriptor = 105;
    public static final int KEY_DESCRIPTOR_FIELD_NUMBER = 105;
    private boolean hasKeyDescriptor;
    private java.lang.String keyDescriptor_ = "";
    public boolean hasKeyDescriptor() { return hasKeyDescriptor; }
    public java.lang.String getKeyDescriptor() { return keyDescriptor_; }
    
    // optional uint64 target_decomp_size = 106;
    public static final int TARGET_DECOMP_SIZE_FIELD_NUMBER = 106;
    private boolean hasTargetDecompSize;
    private long targetDecompSize_ = 0L;
    public boolean hasTargetDecompSize() { return hasTargetDecompSize; }
    public long getTargetDecompSize() { return targetDecompSize_; }
    
    // optional uint64 index_offset = 200;
    public static final int INDEX_OFFSET_FIELD_NUMBER = 200;
    private boolean hasIndexOffset;
    private long indexOffset_ = 0L;
    public boolean hasIndexOffset() { return hasIndexOffset; }
    public long getIndexOffset() { return indexOffset_; }
    
    // optional uint64 index_bytes = 201;
    public static final int INDEX_BYTES_FIELD_NUMBER = 201;
    private boolean hasIndexBytes;
    private long indexBytes_ = 0L;
    public boolean hasIndexBytes() { return hasIndexBytes; }
    public long getIndexBytes() { return indexBytes_; }
    
    // optional bytes first_key = 202;
    public static final int FIRST_KEY_FIELD_NUMBER = 202;
    private boolean hasFirstKey;
    private com.google.protobuf.ByteString firstKey_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasFirstKey() { return hasFirstKey; }
    public com.google.protobuf.ByteString getFirstKey() { return firstKey_; }
    
    // optional bytes last_key = 203;
    public static final int LAST_KEY_FIELD_NUMBER = 203;
    private boolean hasLastKey;
    private com.google.protobuf.ByteString lastKey_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasLastKey() { return hasLastKey; }
    public com.google.protobuf.ByteString getLastKey() { return lastKey_; }
    
    // optional uint64 message_count = 204;
    public static final int MESSAGE_COUNT_FIELD_NUMBER = 204;
    private boolean hasMessageCount;
    private long messageCount_ = 0L;
    public boolean hasMessageCount() { return hasMessageCount; }
    public long getMessageCount() { return messageCount_; }
    
    // optional uint64 data_block_count = 205;
    public static final int DATA_BLOCK_COUNT_FIELD_NUMBER = 205;
    private boolean hasDataBlockCount;
    private long dataBlockCount_ = 0L;
    public boolean hasDataBlockCount() { return hasDataBlockCount; }
    public long getDataBlockCount() { return dataBlockCount_; }
    
    // optional uint64 uncompressed_bytes = 206;
    public static final int UNCOMPRESSED_BYTES_FIELD_NUMBER = 206;
    private boolean hasUncompressedBytes;
    private long uncompressedBytes_ = 0L;
    public boolean hasUncompressedBytes() { return hasUncompressedBytes; }
    public long getUncompressedBytes() { return uncompressedBytes_; }
    
    // optional uint64 max_decomp_size = 207;
    public static final int MAX_DECOMP_SIZE_FIELD_NUMBER = 207;
    private boolean hasMaxDecompSize;
    private long maxDecompSize_ = 0L;
    public boolean hasMaxDecompSize() { return hasMaxDecompSize; }
    public long getMaxDecompSize() { return maxDecompSize_; }
    
    // repeated bytes format_descriptor = 301;
    public static final int FORMAT_DESCRIPTOR_FIELD_NUMBER = 301;
    private java.util.List<com.google.protobuf.ByteString> formatDescriptor_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getFormatDescriptorList() {
      return formatDescriptor_;
    }
    public int getFormatDescriptorCount() { return formatDescriptor_.size(); }
    public com.google.protobuf.ByteString getFormatDescriptor(int index) {
      return formatDescriptor_.get(index);
    }
    
    // optional uint32 metadata_count = 302;
    public static final int METADATA_COUNT_FIELD_NUMBER = 302;
    private boolean hasMetadataCount;
    private int metadataCount_ = 0;
    public boolean hasMetadataCount() { return hasMetadataCount; }
    public int getMetadataCount() { return metadataCount_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCopyrightNotice()) {
        output.writeString(100, getCopyrightNotice());
      }
      if (hasPartitionCount()) {
        output.writeUInt32(101, getPartitionCount());
      }
      if (hasPartitionNumber()) {
        output.writeUInt32(102, getPartitionNumber());
      }
      if (hasInitialPipeName()) {
        output.writeString(103, getInitialPipeName());
      }
      if (hasMessageName()) {
        output.writeString(104, getMessageName());
      }
      if (hasKeyDescriptor()) {
        output.writeString(105, getKeyDescriptor());
      }
      if (hasTargetDecompSize()) {
        output.writeUInt64(106, getTargetDecompSize());
      }
      if (hasIndexOffset()) {
        output.writeUInt64(200, getIndexOffset());
      }
      if (hasIndexBytes()) {
        output.writeUInt64(201, getIndexBytes());
      }
      if (hasFirstKey()) {
        output.writeBytes(202, getFirstKey());
      }
      if (hasLastKey()) {
        output.writeBytes(203, getLastKey());
      }
      if (hasMessageCount()) {
        output.writeUInt64(204, getMessageCount());
      }
      if (hasDataBlockCount()) {
        output.writeUInt64(205, getDataBlockCount());
      }
      if (hasUncompressedBytes()) {
        output.writeUInt64(206, getUncompressedBytes());
      }
      if (hasMaxDecompSize()) {
        output.writeUInt64(207, getMaxDecompSize());
      }
      for (com.google.protobuf.ByteString element : getFormatDescriptorList()) {
        output.writeBytes(301, element);
      }
      if (hasMetadataCount()) {
        output.writeUInt32(302, getMetadataCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCopyrightNotice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(100, getCopyrightNotice());
      }
      if (hasPartitionCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(101, getPartitionCount());
      }
      if (hasPartitionNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(102, getPartitionNumber());
      }
      if (hasInitialPipeName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(103, getInitialPipeName());
      }
      if (hasMessageName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(104, getMessageName());
      }
      if (hasKeyDescriptor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(105, getKeyDescriptor());
      }
      if (hasTargetDecompSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(106, getTargetDecompSize());
      }
      if (hasIndexOffset()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(200, getIndexOffset());
      }
      if (hasIndexBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(201, getIndexBytes());
      }
      if (hasFirstKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(202, getFirstKey());
      }
      if (hasLastKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(203, getLastKey());
      }
      if (hasMessageCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(204, getMessageCount());
      }
      if (hasDataBlockCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(205, getDataBlockCount());
      }
      if (hasUncompressedBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(206, getUncompressedBytes());
      }
      if (hasMaxDecompSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(207, getMaxDecompSize());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getFormatDescriptorList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 2 * getFormatDescriptorList().size();
      }
      if (hasMetadataCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(302, getMetadataCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private tap.formats.tapproto.Tapfile.Header result;
      
      // Construct using tap.formats.tapproto.Tapfile.Header.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new tap.formats.tapproto.Tapfile.Header();
        return builder;
      }
      
      protected tap.formats.tapproto.Tapfile.Header internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new tap.formats.tapproto.Tapfile.Header();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.Header.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.Header getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.Header.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public tap.formats.tapproto.Tapfile.Header build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private tap.formats.tapproto.Tapfile.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public tap.formats.tapproto.Tapfile.Header buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.formatDescriptor_ != java.util.Collections.EMPTY_LIST) {
          result.formatDescriptor_ =
            java.util.Collections.unmodifiableList(result.formatDescriptor_);
        }
        tap.formats.tapproto.Tapfile.Header returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.Header) {
          return mergeFrom((tap.formats.tapproto.Tapfile.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.Header other) {
        if (other == tap.formats.tapproto.Tapfile.Header.getDefaultInstance()) return this;
        if (other.hasCopyrightNotice()) {
          setCopyrightNotice(other.getCopyrightNotice());
        }
        if (other.hasPartitionCount()) {
          setPartitionCount(other.getPartitionCount());
        }
        if (other.hasPartitionNumber()) {
          setPartitionNumber(other.getPartitionNumber());
        }
        if (other.hasInitialPipeName()) {
          setInitialPipeName(other.getInitialPipeName());
        }
        if (other.hasMessageName()) {
          setMessageName(other.getMessageName());
        }
        if (other.hasKeyDescriptor()) {
          setKeyDescriptor(other.getKeyDescriptor());
        }
        if (other.hasTargetDecompSize()) {
          setTargetDecompSize(other.getTargetDecompSize());
        }
        if (other.hasIndexOffset()) {
          setIndexOffset(other.getIndexOffset());
        }
        if (other.hasIndexBytes()) {
          setIndexBytes(other.getIndexBytes());
        }
        if (other.hasFirstKey()) {
          setFirstKey(other.getFirstKey());
        }
        if (other.hasLastKey()) {
          setLastKey(other.getLastKey());
        }
        if (other.hasMessageCount()) {
          setMessageCount(other.getMessageCount());
        }
        if (other.hasDataBlockCount()) {
          setDataBlockCount(other.getDataBlockCount());
        }
        if (other.hasUncompressedBytes()) {
          setUncompressedBytes(other.getUncompressedBytes());
        }
        if (other.hasMaxDecompSize()) {
          setMaxDecompSize(other.getMaxDecompSize());
        }
        if (!other.formatDescriptor_.isEmpty()) {
          if (result.formatDescriptor_.isEmpty()) {
            result.formatDescriptor_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.formatDescriptor_.addAll(other.formatDescriptor_);
        }
        if (other.hasMetadataCount()) {
          setMetadataCount(other.getMetadataCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          System.out.println("read tag " + tag);
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 802: {
              setCopyrightNotice(input.readString());
              break;
            }
            case 808: {
              setPartitionCount(input.readUInt32());
              break;
            }
            case 816: {
              setPartitionNumber(input.readUInt32());
              break;
            }
            case 826: {
              setInitialPipeName(input.readString());
              break;
            }
            case 834: {
              setMessageName(input.readString());
              break;
            }
            case 842: {
              setKeyDescriptor(input.readString());
              break;
            }
            case 848: {
              setTargetDecompSize(input.readUInt64());
              break;
            }
            case 1600: {
              setIndexOffset(input.readUInt64());
              break;
            }
            case 1608: {
              setIndexBytes(input.readUInt64());
              break;
            }
            case 1618: {
              setFirstKey(input.readBytes());
              break;
            }
            case 1626: {
              setLastKey(input.readBytes());
              break;
            }
            case 1632: {
              setMessageCount(input.readUInt64());
              break;
            }
            case 1640: {
              setDataBlockCount(input.readUInt64());
              break;
            }
            case 1648: {
              setUncompressedBytes(input.readUInt64());
              break;
            }
            case 1656: {
              setMaxDecompSize(input.readUInt64());
              break;
            }
            case 2410: {
                System.out.println("before addFormatDescriptor");
              addFormatDescriptor(input.readBytes());
                System.out.println("after addFormatDescriptor");
              break;
            }
            case 2416: {
              setMetadataCount(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string copyright_notice = 100;
      public boolean hasCopyrightNotice() {
        return result.hasCopyrightNotice();
      }
      public java.lang.String getCopyrightNotice() {
        return result.getCopyrightNotice();
      }
      public Builder setCopyrightNotice(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCopyrightNotice = true;
        result.copyrightNotice_ = value;
        return this;
      }
      public Builder clearCopyrightNotice() {
        result.hasCopyrightNotice = false;
        result.copyrightNotice_ = getDefaultInstance().getCopyrightNotice();
        return this;
      }
      
      // optional uint32 partition_count = 101;
      public boolean hasPartitionCount() {
        return result.hasPartitionCount();
      }
      public int getPartitionCount() {
        return result.getPartitionCount();
      }
      public Builder setPartitionCount(int value) {
        result.hasPartitionCount = true;
        result.partitionCount_ = value;
        return this;
      }
      public Builder clearPartitionCount() {
        result.hasPartitionCount = false;
        result.partitionCount_ = 0;
        return this;
      }
      
      // optional uint32 partition_number = 102;
      public boolean hasPartitionNumber() {
        return result.hasPartitionNumber();
      }
      public int getPartitionNumber() {
        return result.getPartitionNumber();
      }
      public Builder setPartitionNumber(int value) {
        result.hasPartitionNumber = true;
        result.partitionNumber_ = value;
        return this;
      }
      public Builder clearPartitionNumber() {
        result.hasPartitionNumber = false;
        result.partitionNumber_ = 0;
        return this;
      }
      
      // optional string initial_pipe_name = 103;
      public boolean hasInitialPipeName() {
        return result.hasInitialPipeName();
      }
      public java.lang.String getInitialPipeName() {
        return result.getInitialPipeName();
      }
      public Builder setInitialPipeName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasInitialPipeName = true;
        result.initialPipeName_ = value;
        return this;
      }
      public Builder clearInitialPipeName() {
        result.hasInitialPipeName = false;
        result.initialPipeName_ = getDefaultInstance().getInitialPipeName();
        return this;
      }
      
      // optional string message_name = 104;
      public boolean hasMessageName() {
        return result.hasMessageName();
      }
      public java.lang.String getMessageName() {
        return result.getMessageName();
      }
      public Builder setMessageName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageName = true;
        result.messageName_ = value;
        return this;
      }
      public Builder clearMessageName() {
        result.hasMessageName = false;
        result.messageName_ = getDefaultInstance().getMessageName();
        return this;
      }
      
      // optional string key_descriptor = 105;
      public boolean hasKeyDescriptor() {
        return result.hasKeyDescriptor();
      }
      public java.lang.String getKeyDescriptor() {
        return result.getKeyDescriptor();
      }
      public Builder setKeyDescriptor(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKeyDescriptor = true;
        result.keyDescriptor_ = value;
        return this;
      }
      public Builder clearKeyDescriptor() {
        result.hasKeyDescriptor = false;
        result.keyDescriptor_ = getDefaultInstance().getKeyDescriptor();
        return this;
      }
      
      // optional uint64 target_decomp_size = 106;
      public boolean hasTargetDecompSize() {
        return result.hasTargetDecompSize();
      }
      public long getTargetDecompSize() {
        return result.getTargetDecompSize();
      }
      public Builder setTargetDecompSize(long value) {
        result.hasTargetDecompSize = true;
        result.targetDecompSize_ = value;
        return this;
      }
      public Builder clearTargetDecompSize() {
        result.hasTargetDecompSize = false;
        result.targetDecompSize_ = 0L;
        return this;
      }
      
      // optional uint64 index_offset = 200;
      public boolean hasIndexOffset() {
        return result.hasIndexOffset();
      }
      public long getIndexOffset() {
        return result.getIndexOffset();
      }
      public Builder setIndexOffset(long value) {
        result.hasIndexOffset = true;
        result.indexOffset_ = value;
        return this;
      }
      public Builder clearIndexOffset() {
        result.hasIndexOffset = false;
        result.indexOffset_ = 0L;
        return this;
      }
      
      // optional uint64 index_bytes = 201;
      public boolean hasIndexBytes() {
        return result.hasIndexBytes();
      }
      public long getIndexBytes() {
        return result.getIndexBytes();
      }
      public Builder setIndexBytes(long value) {
        result.hasIndexBytes = true;
        result.indexBytes_ = value;
        return this;
      }
      public Builder clearIndexBytes() {
        result.hasIndexBytes = false;
        result.indexBytes_ = 0L;
        return this;
      }
      
      // optional bytes first_key = 202;
      public boolean hasFirstKey() {
        return result.hasFirstKey();
      }
      public com.google.protobuf.ByteString getFirstKey() {
        return result.getFirstKey();
      }
      public Builder setFirstKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFirstKey = true;
        result.firstKey_ = value;
        return this;
      }
      public Builder clearFirstKey() {
        result.hasFirstKey = false;
        result.firstKey_ = getDefaultInstance().getFirstKey();
        return this;
      }
      
      // optional bytes last_key = 203;
      public boolean hasLastKey() {
        return result.hasLastKey();
      }
      public com.google.protobuf.ByteString getLastKey() {
        return result.getLastKey();
      }
      public Builder setLastKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLastKey = true;
        result.lastKey_ = value;
        return this;
      }
      public Builder clearLastKey() {
        result.hasLastKey = false;
        result.lastKey_ = getDefaultInstance().getLastKey();
        return this;
      }
      
      // optional uint64 message_count = 204;
      public boolean hasMessageCount() {
        return result.hasMessageCount();
      }
      public long getMessageCount() {
        return result.getMessageCount();
      }
      public Builder setMessageCount(long value) {
        result.hasMessageCount = true;
        result.messageCount_ = value;
        return this;
      }
      public Builder clearMessageCount() {
        result.hasMessageCount = false;
        result.messageCount_ = 0L;
        return this;
      }
      
      // optional uint64 data_block_count = 205;
      public boolean hasDataBlockCount() {
        return result.hasDataBlockCount();
      }
      public long getDataBlockCount() {
        return result.getDataBlockCount();
      }
      public Builder setDataBlockCount(long value) {
        result.hasDataBlockCount = true;
        result.dataBlockCount_ = value;
        return this;
      }
      public Builder clearDataBlockCount() {
        result.hasDataBlockCount = false;
        result.dataBlockCount_ = 0L;
        return this;
      }
      
      // optional uint64 uncompressed_bytes = 206;
      public boolean hasUncompressedBytes() {
        return result.hasUncompressedBytes();
      }
      public long getUncompressedBytes() {
        return result.getUncompressedBytes();
      }
      public Builder setUncompressedBytes(long value) {
        result.hasUncompressedBytes = true;
        result.uncompressedBytes_ = value;
        return this;
      }
      public Builder clearUncompressedBytes() {
        result.hasUncompressedBytes = false;
        result.uncompressedBytes_ = 0L;
        return this;
      }
      
      // optional uint64 max_decomp_size = 207;
      public boolean hasMaxDecompSize() {
        return result.hasMaxDecompSize();
      }
      public long getMaxDecompSize() {
        return result.getMaxDecompSize();
      }
      public Builder setMaxDecompSize(long value) {
        result.hasMaxDecompSize = true;
        result.maxDecompSize_ = value;
        return this;
      }
      public Builder clearMaxDecompSize() {
        result.hasMaxDecompSize = false;
        result.maxDecompSize_ = 0L;
        return this;
      }
      
      // repeated bytes format_descriptor = 301;
      public java.util.List<com.google.protobuf.ByteString> getFormatDescriptorList() {
        return java.util.Collections.unmodifiableList(result.formatDescriptor_);
      }
      public int getFormatDescriptorCount() {
        return result.getFormatDescriptorCount();
      }
      public com.google.protobuf.ByteString getFormatDescriptor(int index) {
        return result.getFormatDescriptor(index);
      }
      public Builder setFormatDescriptor(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.formatDescriptor_.set(index, value);
        return this;
      }
      public Builder addFormatDescriptor(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.formatDescriptor_.isEmpty()) {
          result.formatDescriptor_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.formatDescriptor_.add(value);
        return this;
      }
      public Builder addAllFormatDescriptor(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.formatDescriptor_.isEmpty()) {
          result.formatDescriptor_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.formatDescriptor_);
        return this;
      }
      public Builder clearFormatDescriptor() {
        result.formatDescriptor_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 metadata_count = 302;
      public boolean hasMetadataCount() {
        return result.hasMetadataCount();
      }
      public int getMetadataCount() {
        return result.getMetadataCount();
      }
      public Builder setMetadataCount(int value) {
        result.hasMetadataCount = true;
        result.metadataCount_ = value;
        return this;
      }
      public Builder clearMetadataCount() {
        result.hasMetadataCount = false;
        result.metadataCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.Header)
    }
    
    static {
      defaultInstance = new Header(true);
      tap.formats.tapproto.Tapfile.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.Header)
  }
  
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessage {
    // Use Metadata.newBuilder() to construct.
    private Metadata() {
      initFields();
    }
    private Metadata(boolean noInit) {}
    
    private static final Metadata defaultInstance;
    public static Metadata getDefaultInstance() {
      return defaultInstance;
    }
    
    public Metadata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Metadata_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tap.formats.tapproto.Tapfile.internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable;
    }
    
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // optional string string_value = 2;
    public static final int STRING_VALUE_FIELD_NUMBER = 2;
    private boolean hasStringValue;
    private java.lang.String stringValue_ = "";
    public boolean hasStringValue() { return hasStringValue; }
    public java.lang.String getStringValue() { return stringValue_; }
    
    // optional uint64 integer_value = 3;
    public static final int INTEGER_VALUE_FIELD_NUMBER = 3;
    private boolean hasIntegerValue;
    private long integerValue_ = 0L;
    public boolean hasIntegerValue() { return hasIntegerValue; }
    public long getIntegerValue() { return integerValue_; }
    
    // optional double double_value = 4;
    public static final int DOUBLE_VALUE_FIELD_NUMBER = 4;
    private boolean hasDoubleValue;
    private double doubleValue_ = 0D;
    public boolean hasDoubleValue() { return hasDoubleValue; }
    public double getDoubleValue() { return doubleValue_; }
    
    // optional bytes bytes_value = 5;
    public static final int BYTES_VALUE_FIELD_NUMBER = 5;
    private boolean hasBytesValue;
    private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBytesValue() { return hasBytesValue; }
    public com.google.protobuf.ByteString getBytesValue() { return bytesValue_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasStringValue()) {
        output.writeString(2, getStringValue());
      }
      if (hasIntegerValue()) {
        output.writeUInt64(3, getIntegerValue());
      }
      if (hasDoubleValue()) {
        output.writeDouble(4, getDoubleValue());
      }
      if (hasBytesValue()) {
        output.writeBytes(5, getBytesValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasStringValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getStringValue());
      }
      if (hasIntegerValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getIntegerValue());
      }
      if (hasDoubleValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, getDoubleValue());
      }
      if (hasBytesValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBytesValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tap.formats.tapproto.Tapfile.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tap.formats.tapproto.Tapfile.Metadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private tap.formats.tapproto.Tapfile.Metadata result;
      
      // Construct using tap.formats.tapproto.Tapfile.Metadata.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new tap.formats.tapproto.Tapfile.Metadata();
        return builder;
      }
      
      protected tap.formats.tapproto.Tapfile.Metadata internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new tap.formats.tapproto.Tapfile.Metadata();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tap.formats.tapproto.Tapfile.Metadata.getDescriptor();
      }
      
      public tap.formats.tapproto.Tapfile.Metadata getDefaultInstanceForType() {
        return tap.formats.tapproto.Tapfile.Metadata.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public tap.formats.tapproto.Tapfile.Metadata build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private tap.formats.tapproto.Tapfile.Metadata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public tap.formats.tapproto.Tapfile.Metadata buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        tap.formats.tapproto.Tapfile.Metadata returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tap.formats.tapproto.Tapfile.Metadata) {
          return mergeFrom((tap.formats.tapproto.Tapfile.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tap.formats.tapproto.Tapfile.Metadata other) {
        if (other == tap.formats.tapproto.Tapfile.Metadata.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasStringValue()) {
          setStringValue(other.getStringValue());
        }
        if (other.hasIntegerValue()) {
          setIntegerValue(other.getIntegerValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasBytesValue()) {
          setBytesValue(other.getBytesValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setStringValue(input.readString());
              break;
            }
            case 24: {
              setIntegerValue(input.readUInt64());
              break;
            }
            case 33: {
              setDoubleValue(input.readDouble());
              break;
            }
            case 42: {
              setBytesValue(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional string string_value = 2;
      public boolean hasStringValue() {
        return result.hasStringValue();
      }
      public java.lang.String getStringValue() {
        return result.getStringValue();
      }
      public Builder setStringValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStringValue = true;
        result.stringValue_ = value;
        return this;
      }
      public Builder clearStringValue() {
        result.hasStringValue = false;
        result.stringValue_ = getDefaultInstance().getStringValue();
        return this;
      }
      
      // optional uint64 integer_value = 3;
      public boolean hasIntegerValue() {
        return result.hasIntegerValue();
      }
      public long getIntegerValue() {
        return result.getIntegerValue();
      }
      public Builder setIntegerValue(long value) {
        result.hasIntegerValue = true;
        result.integerValue_ = value;
        return this;
      }
      public Builder clearIntegerValue() {
        result.hasIntegerValue = false;
        result.integerValue_ = 0L;
        return this;
      }
      
      // optional double double_value = 4;
      public boolean hasDoubleValue() {
        return result.hasDoubleValue();
      }
      public double getDoubleValue() {
        return result.getDoubleValue();
      }
      public Builder setDoubleValue(double value) {
        result.hasDoubleValue = true;
        result.doubleValue_ = value;
        return this;
      }
      public Builder clearDoubleValue() {
        result.hasDoubleValue = false;
        result.doubleValue_ = 0D;
        return this;
      }
      
      // optional bytes bytes_value = 5;
      public boolean hasBytesValue() {
        return result.hasBytesValue();
      }
      public com.google.protobuf.ByteString getBytesValue() {
        return result.getBytesValue();
      }
      public Builder setBytesValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBytesValue = true;
        result.bytesValue_ = value;
        return this;
      }
      public Builder clearBytesValue() {
        result.hasBytesValue = false;
        result.bytesValue_ = getDefaultInstance().getBytesValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tap.formats.tapproto.Metadata)
    }
    
    static {
      defaultInstance = new Metadata(true);
      tap.formats.tapproto.Tapfile.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tap.formats.tapproto.Metadata)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_LowerIndexEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_LowerIndexEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_UpperIndexEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_UpperIndexEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tap_formats_tapproto_Metadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtapfile.proto\022\024tap.formats.tapproto\"4\n" +
      "\017LowerIndexEntry\022\013\n\003key\030\001 \001(\014\022\024\n\014message" +
      "_size\030\002 \001(\r\"\233\001\n\017UpperIndexEntry\022\021\n\tfirst" +
      "_key\030\001 \001(\014\022\023\n\013data_offset\030\002 \001(\004\022\022\n\ndata_" +
      "bytes\030\003 \001(\004\022\032\n\022lower_index_offset\030\004 \001(\004\022" +
      "\031\n\021lower_index_bytes\030\005 \001(\004\022\025\n\rmessage_co" +
      "unt\030\006 \001(\r\"\255\003\n\006Header\022\030\n\020copyright_notice" +
      "\030d \001(\t\022\027\n\017partition_count\030e \001(\r\022\030\n\020parti" +
      "tion_number\030f \001(\r\022\031\n\021initial_pipe_name\030g" +
      " \001(\t\022\024\n\014message_name\030h \001(\t\022\026\n\016key_descri",
      "ptor\030i \001(\t\022\032\n\022target_decomp_size\030j \001(\004\022\025" +
      "\n\014index_offset\030\310\001 \001(\004\022\024\n\013index_bytes\030\311\001 " +
      "\001(\004\022\022\n\tfirst_key\030\312\001 \001(\014\022\021\n\010last_key\030\313\001 \001" +
      "(\014\022\026\n\rmessage_count\030\314\001 \001(\004\022\031\n\020data_block" +
      "_count\030\315\001 \001(\004\022\033\n\022uncompressed_bytes\030\316\001 \001" +
      "(\004\022\030\n\017max_decomp_size\030\317\001 \001(\004\022\032\n\021format_d" +
      "escriptor\030\255\002 \003(\014\022\027\n\016metadata_count\030\256\002 \001(" +
      "\r\"o\n\010Metadata\022\013\n\003key\030\001 \001(\t\022\024\n\014string_val" +
      "ue\030\002 \001(\t\022\025\n\rinteger_value\030\003 \001(\004\022\024\n\014doubl" +
      "e_value\030\004 \001(\001\022\023\n\013bytes_value\030\005 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tap_formats_tapproto_LowerIndexEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tap_formats_tapproto_LowerIndexEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_LowerIndexEntry_descriptor,
              new java.lang.String[] { "Key", "MessageSize", },
              tap.formats.tapproto.Tapfile.LowerIndexEntry.class,
              tap.formats.tapproto.Tapfile.LowerIndexEntry.Builder.class);
          internal_static_tap_formats_tapproto_UpperIndexEntry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tap_formats_tapproto_UpperIndexEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_UpperIndexEntry_descriptor,
              new java.lang.String[] { "FirstKey", "DataOffset", "DataBytes", "LowerIndexOffset", "LowerIndexBytes", "MessageCount", },
              tap.formats.tapproto.Tapfile.UpperIndexEntry.class,
              tap.formats.tapproto.Tapfile.UpperIndexEntry.Builder.class);
          internal_static_tap_formats_tapproto_Header_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tap_formats_tapproto_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_Header_descriptor,
              new java.lang.String[] { "CopyrightNotice", "PartitionCount", "PartitionNumber", "InitialPipeName", "MessageName", "KeyDescriptor", "TargetDecompSize", "IndexOffset", "IndexBytes", "FirstKey", "LastKey", "MessageCount", "DataBlockCount", "UncompressedBytes", "MaxDecompSize", "FormatDescriptor", "MetadataCount", },
              tap.formats.tapproto.Tapfile.Header.class,
              tap.formats.tapproto.Tapfile.Header.Builder.class);
          internal_static_tap_formats_tapproto_Metadata_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_tap_formats_tapproto_Metadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tap_formats_tapproto_Metadata_descriptor,
              new java.lang.String[] { "Key", "StringValue", "IntegerValue", "DoubleValue", "BytesValue", },
              tap.formats.tapproto.Tapfile.Metadata.class,
              tap.formats.tapproto.Tapfile.Metadata.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
